import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

// https://youtrack.jetbrains.com/issue/KTIJ-24981
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version("0.4.0")
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenLocal()
        google()
        mavenCentral()
    }
}

rootProject.name = "android-fore"

//include(":fore-kt")
include(':lib:fore-core')
include(':lib:fore-net')
include(':lib:fore-net-okhttp3v3x')
include(":lib:fore-net-okhttp3v4x")

// kotlin android
//include(":fore-kt:fore-kt-android") // everything
//include(":lib:fore-kt-android-core")
//include(":fore-kt:fore-kt-android-adapters")
//include(":fore-kt:fore-kt-android-network")
//include(":fore-kt:fore-kt-android-compose")
//
//include(":app-examples")
include(":app-examples:example-kt-01reactiveui",
        ":app-examples:example-kt-02coroutine",
//        ":app-examples:example-kt-03adapters",
//        ":app-examples:example-kt-04retrofit",
//        ":app-examples:example-kt-07apollo3",
        ":app-examples:example-kt-08ktor")
//        ":app-examples:example-kt-09compose",
//        ":app-examples:example-jv-01reactiveui",
//        ":app-examples:example-jv-02threading",
//        ":app-examples:example-jv-03adapters",
//        ":app-examples:example-jv-04retrofit",
//        ":app-examples:example-jv-06db")
