import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

// https://youtrack.jetbrains.com/issue/KTIJ-24981
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version("0.4.0")
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenLocal()
        google()
        mavenCentral()
    }
}

rootProject.name = "android-fore"

include(':lib:fore-core')
include(':lib:fore-net')
include(':lib:fore-compose')
include(':lib:fore-test-fixtures')

include(':lib:fore-net-apollo')
include(':lib:fore-net-apollo-test-fixtures')

// kotlin android
//include(":fore-kt:fore-kt-android") // everything
//include(":lib:fore-kt-android-core")
//include(":fore-kt:fore-kt-android-adapters")
//include(":fore-kt:fore-kt-android-network")
//include(":fore-kt:fore-kt-android-compose")
//
//include(":app-examples")
include(':app-examples:example-01-reactiveui',
        ':app-examples:example-02-coroutine',
        ':app-examples:example-03-ktor',
        ':app-examples:example-04-apollo',
        ':app-examples:example-06-compose-android')
