version: 2 #circleci yml api version
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=true
    steps:
      - checkout
      - restore_cache:
          # bump the cache version number if you want to wipe the gradle cache
          key: v4-gradle-dependencies-cache
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v4-gradle-dependencies-cache

      - run:
          name: Run Tests fore-core
          command: ./gradlew fore-core:lintRelease fore-core:testRelease
      - store_artifacts:
          path: fore-core/build/reports
      - store_test_results:
          path: fore-core/build/test-results

      - run:
          name: Run Tests fore-core-kt
          command: ./gradlew fore-core-kt:lintRelease fore-core-kt:testRelease
      - store_artifacts:
          path: fore-core-kt/build/reports
      - store_test_results:
          path: fore-core-kt/build/test-results

      - run:
          name: Run Tests fore-adapters
          command: ./gradlew fore-adapters:lintRelease fore-adapters:testRelease
      - store_artifacts:
          path: fore-adapters/build/reports
      - store_test_results:
          path: fore-adapters/build/test-results

      - run:
          name: Run Tests fore-adapters-kt
          command: ./gradlew fore-adapters-kt:lintRelease fore-adapters-kt:testRelease
      - store_artifacts:
          path: fore-adapters-kt/build/reports
      - store_test_results:
          path: fore-adapters-kt/build/test-results

      - run:
          name: Run Tests fore-retrofit
          command: ./gradlew fore-retrofit:lintRelease fore-retrofit:testRelease
      - store_artifacts:
          path: fore-retrofit/build/reports
      - store_test_results:
          path: fore-retrofit/build/test-results

      - run:
          name: Run Tests fore-retrofit-kt
          command: ./gradlew fore-retrofit-kt:lintRelease fore-retrofit-kt:testRelease
      - store_artifacts:
          path: fore-retrofit-kt/build/reports
      - store_test_results:
          path: fore-retrofit-kt/build/test-results

      - run:
          name: Run Tests fore-lifecycle
          command: ./gradlew fore-lifecycle:lintRelease fore-lifecycle:testRelease
      - store_artifacts:
          path: fore-lifecycle/build/reports
      - store_test_results:
          path: fore-lifecycle/build/test-results

      - run:
          name: Run Tests example01databinding
          command: ./gradlew example01databinding:lintRelease example01databinding:testRelease
      - store_artifacts:
          path: example01databinding/build/reports
      - store_test_results:
          path: example01databinding/build/test-results

      - run:
          name: Run Tests example02threading
          command: ./gradlew example02threading:lintRelease example02threading:testRelease
      - store_artifacts:
          path: example02threading/build/reports
      - store_test_results:
          path: example02threading/build/test-results

      - run:
          name: Run Tests example03adapters
          command: ./gradlew example03adapters:lintRelease example03adapters:testRelease
      - store_artifacts:
          path: example03adapters/build/reports
      - store_test_results:
          path: example03adapters/build/test-results

      - run:
          name: Run Tests example04retrofit
          command: ./gradlew example04retrofit:lintRelease example04retrofit:testRelease
      - store_artifacts:
          path: example04retrofit/build/reports
      - store_test_results:
          path: example04retrofit/build/test-results

      - run:
          name: Run Tests example05ui
          command: ./gradlew example05ui:lintRelease example05ui:testRelease
      - store_artifacts:
          path: example05ui/build/reports
      - store_test_results:
          path: example05ui/build/test-results

      - run:
          name: Run Tests example06db
          command: ./gradlew example06db:lintRelease example06db:testRelease
      - store_artifacts:
          path: example06db/build/reports
      - store_test_results:
          path: example06db/build/test-results

      - run:
          name: Run Tests example-kt-02coroutine
          command: ./gradlew example-kt-02coroutine:lintRelease example-kt-02coroutine:testRelease
      - store_artifacts:
          path: example-kt-02coroutine/build/reports
      - store_test_results:
          path: example-kt-02coroutine/build/test-results

      - run:
          name: Run Tests example-kt-03adapters
          command: ./gradlew example-kt-03adapters:lintRelease example-kt-03adapters:testRelease
      - store_artifacts:
          path: example-kt-03adapters/build/reports
      - store_test_results:
          path: example-kt-03adapters/build/test-results

      - run:
          name: Run Tests example-kt-04retrofit
          command: ./gradlew example-kt-04retrofit:lintRelease example-kt-04retrofit:testRelease
      - store_artifacts:
          path: example-kt-04retrofit/build/reports
      - store_test_results:
          path: example-kt-04retrofit/build/test-results
