version: 2 #circleci yml api version
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2025.04
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=true
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          # bump the cache version number if you want to wipe the gradle cache
          key: v7-gradle-dependencies-cache
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v7-gradle-dependencies-cache

      - run:
          name: Run Tests fore-compose
          command: ./gradlew lib:fore-compose:lintRelease lib:fore-compose:testRelease
      - store_artifacts:
          path: lib/fore-compose/build/reports
      - store_test_results:
          path: lib/fore-compose/build/test-results

      - run:
          name: Run Tests fore-core
          command: ./gradlew lib:fore-core:lintRelease lib:fore-core:testRelease
      - store_artifacts:
          path: lib/fore-core/build/reports
      - store_test_results:
          path: lib/fore-core/build/test-results

      - run:
          name: Run Tests fore-net
          command: ./gradlew lib:fore-net:lintRelease lib:fore-net:testRelease
      - store_artifacts:
          path: lib/fore-net/build/reports
      - store_test_results:
          path: lib/fore-net/build/test-results

      - run:
          name: Run Tests example-01-reactiveui
          command: ./gradlew app-examples:example-01-reactiveui:lintRelease app-examples:example-01-reactiveui:testRelease
      - store_artifacts:
          path: app-examples/example-01-reactiveui/build/reports
      - store_test_results:
          path: app-examples/example-01-reactiveui/build/test-results

      - run:
          name: Run Tests example-02-coroutine
          command: ./gradlew app-examples:example-02-coroutine:lintRelease app-examples:example-02-coroutine:testRelease
      - store_artifacts:
          path: app-examples/example-02-coroutine/build/reports
      - store_test_results:
          path: app-examples/example-02-coroutine/build/test-results

      - run:
          name: Run Tests example-03-ktor
          command: ./gradlew app-examples:example-03-ktor:lintRelease app-examples:example-03-ktor:testRelease
      - store_artifacts:
          path: app-examples/example-03-ktor/build/reports
      - store_test_results:
          path: app-examples/example-03-ktor/build/test-results

      - run:
          name: Run Tests example-04-apollo
          command: ./gradlew app-examples:example-04-apollo:lintRelease app-examples:example-04-apollo:testRelease
      - store_artifacts:
          path: app-examples/example-04-apollo/build/reports
      - store_test_results:
          path: app-examples/example-04-apollo/build/test-results

#      - run:
#          name: Run Tests example-05-db
#          command: ./gradlew app-examples:example-05-db:lintRelease app-examples:example-05-db:testRelease
#      - store_artifacts:
#          path: app-examples/example-05-db/build/reports
#      - store_test_results:
#          path: app-examples/example-05-db/build/test-results

      - run:
          name: Run Tests example-06-compose
          command: ./gradlew app-examples:example-06-compose:lintRelease app-examples:example-06-compose:testRelease
      - store_artifacts:
          path: app-examples/example-06-compose/build/reports
      - store_test_results:
          path: app-examples/example-06-compose/build/test-results

