version: 2 #circleci yml api version
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=true
    steps:
      - checkout
      - restore_cache:
          # bump the cache version number if you want to wipe the gradle cache
          key: v5-gradle-dependencies-cache
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v5-gradle-dependencies-cache

      - run:
          name: Run Tests fore-jv-android
          command: ./gradlew fore-jv-android:lintRelease fore-jv-android:testRelease
      - store_artifacts:
          path: fore-jv-android/build/reports
      - store_test_results:
          path: fore-jv-android/build/test-results

      - run:
          name: Run Tests fore-kt-android
          command: ./gradlew fore-kt-android:lintRelease fore-kt-android:testRelease
      - store_artifacts:
          path: fore-kt-android/build/reports
      - store_test_results:
          path: fore-kt-android/build/test-results

      - run:
          name: Run Tests example-jv-01reactiveui
          command: ./gradlew example-jv-01reactiveui:lintRelease example-jv-01reactiveui:testRelease
      - store_artifacts:
          path: example-jv-01reactiveui/build/reports
      - store_test_results:
          path: example-jv-01reactiveui/build/test-results

      - run:
          name: Run Tests example-jv-02threading
          command: ./gradlew example-jv-02threading:lintRelease example-jv-02threading:testRelease
      - store_artifacts:
          path: example-jv-02threading/build/reports
      - store_test_results:
          path: example-jv-02threading/build/test-results

      - run:
          name: Run Tests example-jv-03adapters
          command: ./gradlew example-jv-03adapters:lintRelease example-jv-03adapters:testRelease
      - store_artifacts:
          path: example-jv-03adapters/build/reports
      - store_test_results:
          path: example-jv-03adapters/build/test-results

      - run:
          name: Run Tests example-jv-04retrofit
          command: ./gradlew example-jv-04retrofit:lintRelease example-jv-04retrofit:testRelease
      - store_artifacts:
          path: example-jv-04retrofit/build/reports
      - store_test_results:
          path: example-jv-04retrofit/build/test-results

      - run:
          name: Run Tests example-jv-06db
          command: ./gradlew example-jv-06db:lintRelease example-jv-06db:testRelease
      - store_artifacts:
          path: example-jv-06db/build/reports
      - store_test_results:
          path: example-jv-06db/build/test-results

      - run:
          name: Run Tests example-kt-01reactiveui
          command: ./gradlew example-kt-01reactiveui:lintRelease example-kt-01reactiveui:testRelease
      - store_artifacts:
          path: example-kt-01reactiveui/build/reports
      - store_test_results:
          path: example-kt-01reactiveui/build/test-results

      - run:
          name: Run Tests example-kt-02coroutine
          command: ./gradlew example-kt-02coroutine:lintRelease example-kt-02coroutine:testRelease
      - store_artifacts:
          path: example-kt-02coroutine/build/reports
      - store_test_results:
          path: example-kt-02coroutine/build/test-results

      - run:
          name: Run Tests example-kt-03adapters
          command: ./gradlew example-kt-03adapters:lintRelease example-kt-03adapters:testRelease
      - store_artifacts:
          path: example-kt-03adapters/build/reports
      - store_test_results:
          path: example-kt-03adapters/build/test-results

      - run:
          name: Run Tests example-kt-04retrofit
          command: ./gradlew example-kt-04retrofit:lintRelease example-kt-04retrofit:testRelease
      - store_artifacts:
          path: example-kt-04retrofit/build/reports
      - store_test_results:
          path: example-kt-04retrofit/build/test-results

      - run:
          name: Run Tests example-kt-07apollo
          command: ./gradlew example-kt-07apollo:lintRelease example-kt-07apollo:testRelease
      - store_artifacts:
          path: example-kt-07apollo/build/reports
      - store_test_results:
          path: example-kt-07apollo/build/test-results

      - run:
          name: Run Tests example-kt-07apollo3
          command: ./gradlew example-kt-07apollo3:lintRelease example-kt-07apollo3:testRelease
      - store_artifacts:
          path: example-kt-07apollo3/build/reports
      - store_test_results:
          path: example-kt-07apollo3/build/test-results

      - run:
          name: Run Tests example-kt-08ktor
          command: ./gradlew example-kt-08ktor:lintRelease example-kt-08ktor:testRelease
      - store_artifacts:
          path: example-kt-08ktor/build/reports
      - store_test_results:
          path: example-kt-08ktor/build/test-results
