version: 2 #circleci yml api version
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=true
    steps:
      - checkout
      - restore_cache:
          # bump the cache version number if you want to wipe the gradle cache
          key: v4-gradle-dependencies-cache
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v4-gradle-dependencies-cache

      - run:
          name: Run Tests fore-core
          command: ./gradlew fore-core:lintRelease fore-core:testRelease
      - store_artifacts:
          path: fore-core/build/reports
      - store_test_results:
          path: fore-core/build/test-results

      - run:
          name: Run Tests fore-core-kt
          command: ./gradlew fore-core-kt:lintRelease fore-core-kt:testRelease
      - store_artifacts:
          path: fore-core-kt/build/reports
      - store_test_results:
          path: fore-core-kt/build/test-results

      - run:
          name: Run Tests fore-adapters
          command: ./gradlew fore-adapters:lintRelease fore-adapters:testRelease
      - store_artifacts:
          path: fore-adapters/build/reports
      - store_test_results:
          path: fore-adapters/build/test-results

      - run:
          name: Run Tests fore-adapters-kt
          command: ./gradlew fore-adapters-kt:lintRelease fore-adapters-kt:testRelease
      - store_artifacts:
          path: fore-adapters-kt/build/reports
      - store_test_results:
          path: fore-adapters-kt/build/test-results

      - run:
          name: Run Tests fore-retrofit
          command: ./gradlew fore-retrofit:lintRelease fore-retrofit:testRelease
      - store_artifacts:
          path: fore-retrofit/build/reports
      - store_test_results:
          path: fore-retrofit/build/test-results

      - run:
          name: Run Tests fore-retrofit-kt
          command: ./gradlew fore-retrofit-kt:lintRelease fore-retrofit-kt:testRelease
      - store_artifacts:
          path: fore-retrofit-kt/build/reports
      - store_test_results:
          path: fore-retrofit-kt/build/test-results

      - run:
          name: Run Tests fore-lifecycle
          command: ./gradlew fore-lifecycle:lintRelease fore-lifecycle:testRelease
      - store_artifacts:
          path: fore-lifecycle/build/reports
      - store_test_results:
          path: fore-lifecycle/build/test-results

      - run:
          name: Run Tests example-jv-01reactiveui
          command: ./gradlew example-jv-01reactiveui:lintRelease example-jv-01reactiveui:testRelease
      - store_artifacts:
          path: example-jv-01reactiveui/build/reports
      - store_test_results:
          path: example-jv-01reactiveui/build/test-results

      - run:
          name: Run Tests example-jv-02threading
          command: ./gradlew example-jv-02threading:lintRelease example-jv-02threading:testRelease
      - store_artifacts:
          path: example-jv-02threading/build/reports
      - store_test_results:
          path: example-jv-02threading/build/test-results

      - run:
          name: Run Tests example-jv-03adapters
          command: ./gradlew example-jv-03adapters:lintRelease example-jv-03adapters:testRelease
      - store_artifacts:
          path: example-jv-03adapters/build/reports
      - store_test_results:
          path: example-jv-03adapters/build/test-results

      - run:
          name: Run Tests example-jv-04retrofit
          command: ./gradlew example-jv-04retrofit:lintRelease example-jv-04retrofit:testRelease
      - store_artifacts:
          path: example-jv-04retrofit/build/reports
      - store_test_results:
          path: example-jv-04retrofit/build/test-results

      - run:
          name: Run Tests example-jv-05ui
          command: ./gradlew example-jv-05ui:lintRelease example-jv-05ui:testRelease
      - store_artifacts:
          path: example-jv-05ui/build/reports
      - store_test_results:
          path: example-jv-05ui/build/test-results

      - run:
          name: Run Tests example-jv-06db
          command: ./gradlew example-jv-06db:lintRelease example-jv-06db:testRelease
      - store_artifacts:
          path: example-jv-06db/build/reports
      - store_test_results:
          path: example-jv-06db/build/test-results

      - run:
          name: Run Tests example-kt-01reactiveui
          command: ./gradlew example-kt-01reactiveui:lintRelease example-kt-01reactiveui:testRelease
      - store_artifacts:
          path: example-kt-01reactiveui/build/reports
      - store_test_results:
          path: example-kt-01reactiveui/build/test-results

      - run:
          name: Run Tests example-kt-02coroutine
          command: ./gradlew example-kt-02coroutine:lintRelease example-kt-02coroutine:testRelease
      - store_artifacts:
          path: example-kt-02coroutine/build/reports
      - store_test_results:
          path: example-kt-02coroutine/build/test-results

      - run:
          name: Run Tests example-kt-03adapters
          command: ./gradlew example-kt-03adapters:lintRelease example-kt-03adapters:testRelease
      - store_artifacts:
          path: example-kt-03adapters/build/reports
      - store_test_results:
          path: example-kt-03adapters/build/test-results

      - run:
          name: Run Tests example-kt-04retrofit
          command: ./gradlew example-kt-04retrofit:lintRelease example-kt-04retrofit:testRelease
      - store_artifacts:
          path: example-kt-04retrofit/build/reports
      - store_test_results:
          path: example-kt-04retrofit/build/test-results
