[versions]
androidPluginVersion = "8.5.2"
kotlinVersion = "2.0.20"
kotlinXIoVersion = "0.1.8"
jvm-toolchain = "8"
okhttp3v3 = "3.14.9"
okhttp3v4 = "4.12.0"
okhttp3v5 = "5.0.0-alpha.12"
apollo = "2.5.14"
apollo3 = "3.8.3"
apollo4 = "4.1.1"
retrofit = "2.11.0"
ktor = "3.1.1"
coroutines = "1.10.1"
lifecycle = "2.6.2" # from 2.7.0 onwards lifecycle-livedata-ktx has broken support for minSdk 16

[libraries]
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinVersion" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinVersion" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io", version.ref = "kotlinXIoVersion" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.0"
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
okio = "com.squareup.okio:okio:3.10.2"
okhttp3-v3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3v3" }
okhttp3-v4 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3v4" }
okhttp3-v5 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3v5" }


apollo3-v3 = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo3" }
apollo4 = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo4" }

[plugins]
androidAppPlugin = { id = "com.android.application", version.ref = "androidPluginVersion" }
androidLibraryPlugin = { id = "com.android.library", version.ref = "androidPluginVersion" }
kotlinAndroidPlugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
kotlinJvmPlugin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
kotlinMultiPlatformPlugin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlinVersion" }
kotlinKaptPlugin = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinVersion" }
kotlinSerializationPlugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }
composePlugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
kotlinCocoapodsPlugin = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlinVersion" }
dokkaPlugin = "org.jetbrains.dokka:2.0.0"